#!/bin/bash

VERSION="1.0.0"

# Ensure the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "This script requires root permissions. Please run with sudo."
  exit 1
fi

# Check if sufficient arguments are passed
if [ "$#" -lt 1 ]; then
    echo "Usage:"
    echo "$0 add <hostname> <IP>    - to add an entry"
    echo "$0 delete <hostname>      - to delete an entry"
    echo "$0 list                   - to list all entries"
    echo "$0 --version              - to show script version"
    exit 1
fi

ACTION=$1
HOSTNAME=$2
IP=$3

# Display version information
if [[ $ACTION == "--version" ]]; then
    echo "LDNS - Local DNS version: $VERSION"
    echo ""
    echo "Author: Harisankar P S"
    echo "Email: contact@hsps.in"
    echo "Website: https://hsps.in"
    exit 0
fi

# Validate the IP address format (basic validation)
if [[ $ACTION == "add" && ! $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Error: Invalid IP address format."
    exit 1
fi

case $ACTION in
    add)
        if [ -z "$HOSTNAME" ] || [ -z "$IP" ]; then
            echo "Error: IP and hostname required to add an entry."
            echo "Usage: $0 add <hostname> <IP>"
            exit 1
        fi

        # Check if the hostname already exists
        if grep -q "$HOSTNAME" /etc/hosts; then
            echo "$HOSTNAME already exists in /etc/hosts."
        else
            # Add the new entry
            echo "$IP $HOSTNAME" | tee -a /etc/hosts > /dev/null
            echo "$HOSTNAME added to /etc/hosts."
        fi
        ;;

    delete)
        if [ -z "$HOSTNAME" ]; then
            echo "Error: Hostname required to delete an entry."
            echo "Usage: $0 delete <hostname>"
            exit 1
        fi

        # Check if the hostname exists
        if grep -q "$HOSTNAME" /etc/hosts; then
            # Remove the line containing the hostname
            sed -i "/$HOSTNAME/d" /etc/hosts
            echo "$HOSTNAME removed from /etc/hosts."
        else
            echo "$HOSTNAME not found in /etc/hosts."
        fi
        ;;

    list)
        echo "Listing all hostnames in /etc/hosts:"
        awk '/^[^#]/ && NF >= 2 {print $2}' /etc/hosts
        ;;

    *)
        echo "Invalid action. Use 'add' or 'delete'."
        echo "Usage:"
        echo "$0 add <hostname> <IP>    - to add an entry"
        echo "$0 delete <hostname>      - to delete an entry"
        echo "$0 list                   - to list all entries"
        echo "$0 --version              - to show script version"
        exit 1
        ;;
esac
